### ISSUE TITLE
About  pretrained models....

### ISSUE THREAD

**Issue by NothingToSay99** [FlyEgle/SDWNet#1]
Thanks for your excellent work！
And Is it possible to make your best pre-trained model public？

**Comment by FlyEgle** [comment]
Thank for you attention, the pretrain  will be released later.

**Comment by NothingToSay99** [comment]
> Thank for you attention, the pretrain will be released later.

Thanks for your reply. And will follow your project.

**Comment by simplew2011** [comment]
![image](https://github.com/FlyEgle/SDWNet/assets/66729924/6172977f-0699-4098-87d2-de198df63b6e)
