### ISSUE TITLE
RealBlur测试问题

### ISSUE THREAD

**Issue by liuwenfu1218** [FlyEgle/SDWNet#2]
请问一下realBlur测试脚本的使用方法..可以分享一下嘛

**Comment by FlyEgle** [comment]
evaluate_realblur.py
这个脚本就可以 ，输入两个路径，一个是你预测的图片，一个是GT。
由于计算的时候可能会存在溢出的问题，所以最好手动改一个try，过滤一下计算有问题的图片

**Comment by liuwenfu1218** [comment]
> evaluate_realblur.py 这个脚本就可以 ，输入两个路径，一个是你预测的图片，一个是GT。 由于计算的时候可能会存在溢出的问题，所以最好手动改一个try，过滤一下计算有问题的图片
感谢您的回复，当时我的模型有点bug，调试了以后可以使用了，十分感谢！
另外可以问下您hide数据集您是用多少数据测试的，官方提供的下载链接我总是中断，在别人分享的链接里下载后发现模糊/清晰图像不是成对的

**Comment by FlyEgle** [comment]
![1641888485(1)](https://user-images.githubusercontent.com/26165705/148904381-67c08bd4-ad04-4037-8c92-787d2caa4e41.png)
我这边也没有完全下全，1000张左右，官方链接的那个dropbox总是有问题
