### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by Alex-afka** [FlyEgle/SDWNet#3]
十分感激您的工作，请问如何训练自己的数据集呢，能否给些步骤 十分感谢！

**Comment by FlyEgle** [comment]
可以先参考这个训练脚本：goprol_train.sh
这里有一个config，你可以在config folder里面查看所有的训练配置参数，有两个比较重要的
![1643267105(1)](https://user-images.githubusercontent.com/26165705/151308381-6c1f24f3-9279-4d68-8f8c-816610b8de77.png)
这里就是你自己的数据集的路径，包括Train和Val，每个都包含两个路径，分别是存放的blur和gt数据，格式如下
![1643267193(1)](https://user-images.githubusercontent.com/26165705/151308588-689182e2-b18c-423a-823b-08a2f6ae5a12.png)
配置好后，启动bash脚本，一切顺利就可以开始进行训练了
