### ISSUE TITLE
About AMP and FP16

### ISSUE THREAD

**Issue by wawaa** [FlyEgle/SDWNet#5]
Hello~看到您有 AMP 和 FP16 相关代码，但是 yaml 文件里面都设置的 FALSE，想问下您那边有实验 AMP 的训练生成效果和损失下降情况嘛？

**Comment by FlyEgle** [comment]
FP16会影响一点点，不多

**Comment by wawaa** [comment]
> FP16会影响一点点，不多

嗯嗯嗯感谢！看这种low level任务用AMP的还是少。
